name: Flow Coverage Report

on:
  push:
    paths: ["src/*.js"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34

    - name: Install modules
      run: |
        yarn install

    - name: Run flow coverage on changed files
      run: |
        coverage_report="Flow coverage report:"
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if [ $file != "src/setupProxy.js" ]; then
            # setupProxy.js is not covered by flow.
            coverage_report=$coverage_report"\n"$file$(yarn flow coverage --quiet $file | grep -o ": .*")
          fi
        done
        echo "COVERAGE_REPORT=$coverage_report" >> $GITHUB_ENV
    
    - name: Comment PR
      uses: allthatjazzleo/actions-pull-request-add-comment@v1
      with:
        message: "${{ env.COVERAGE_REPORT }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
