name: JavaScript Code Check

on:
  push:
    paths: ["src/*.js"]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: |
        yarn install
    - name: Analysing the code with ESLint
      run: |
        eslint src --ext .js,.jsx,.ts,.tsx
    - name: Flow type check
      run: |
        flow src