name: Python Code Check

on: 
  push:
    paths: ["class_route_api/*.py"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      continue-on-error: true
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      continue-on-error: true
      run: |
        pylint $(git ls-files 'class_route_api/*.py')
    - name: Analysing the code with yapf
      continue-on-error: true
      run: |
        yapf -d $(git ls-files 'class_route_api/*.py')
    - name: Analysing the imports with isort 
      continue-on-error: true
      run: |
        isort -c $(git ls-files 'class_route_api/*.py')
    - name: Pyright type check
      continue-on-error: true
      run: |
        pyright $(git ls-files 'class_route_api/*.py')
