name: Python Code Check

on: 
  push:
    paths: ["class_route_api/*.py"]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Analysing the code with yapf
      run: |
        yapf $(git ls-files '*.py')
    - name: Analysing the imports with isort 
      run: |
        isort -c $(git ls-files '*.py')
    - name: Pyright type check
      run: |
        pyright $(git ls-files '*.py')
